/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KebijakanRouteImport } from './routes/kebijakan'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTugasRouteImport } from './routes/app.tugas'
import { Route as AppResepRouteImport } from './routes/app.resep'
import { Route as AppKeuanganRouteImport } from './routes/app.keuangan'
import { Route as AppKalenderRouteImport } from './routes/app.kalender'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppBelanjaRouteImport } from './routes/app.belanja'
import { Route as AppAkunRouteImport } from './routes/app.akun'
import { Route as AppResepResepIdRouteImport } from './routes/app.resep.$resepId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanRoute = KebijakanRouteImport.update({
  id: '/kebijakan',
  path: '/kebijakan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTugasRoute = AppTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AppRoute,
} as any)
const AppResepRoute = AppResepRouteImport.update({
  id: '/resep',
  path: '/resep',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppBelanjaRoute = AppBelanjaRouteImport.update({
  id: '/belanja',
  path: '/belanja',
  getParentRoute: () => AppRoute,
} as any)
const AppAkunRoute = AppAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AppRoute,
} as any)
const AppResepResepIdRoute = AppResepResepIdRouteImport.update({
  id: '/$resepId',
  path: '/$resepId',
  getParentRoute: () => AppResepRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/kebijakan': typeof KebijakanRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/akun': typeof AppAkunRoute
  '/app/belanja': typeof AppBelanjaRoute
  '/app/feed': typeof AppFeedRoute
  '/app/kalender': typeof AppKalenderRoute
  '/app/keuangan': typeof AppKeuanganRoute
  '/app/resep': typeof AppResepRouteWithChildren
  '/app/tugas': typeof AppTugasRoute
  '/app/': typeof AppIndexRoute
  '/app/resep/$resepId': typeof AppResepResepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kebijakan': typeof KebijakanRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/akun': typeof AppAkunRoute
  '/app/belanja': typeof AppBelanjaRoute
  '/app/feed': typeof AppFeedRoute
  '/app/kalender': typeof AppKalenderRoute
  '/app/keuangan': typeof AppKeuanganRoute
  '/app/resep': typeof AppResepRouteWithChildren
  '/app/tugas': typeof AppTugasRoute
  '/app': typeof AppIndexRoute
  '/app/resep/$resepId': typeof AppResepResepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/kebijakan': typeof KebijakanRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/akun': typeof AppAkunRoute
  '/app/belanja': typeof AppBelanjaRoute
  '/app/feed': typeof AppFeedRoute
  '/app/kalender': typeof AppKalenderRoute
  '/app/keuangan': typeof AppKeuanganRoute
  '/app/resep': typeof AppResepRouteWithChildren
  '/app/tugas': typeof AppTugasRoute
  '/app/': typeof AppIndexRoute
  '/app/resep/$resepId': typeof AppResepResepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/kebijakan'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/akun'
    | '/app/belanja'
    | '/app/feed'
    | '/app/kalender'
    | '/app/keuangan'
    | '/app/resep'
    | '/app/tugas'
    | '/app/'
    | '/app/resep/$resepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kebijakan'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/akun'
    | '/app/belanja'
    | '/app/feed'
    | '/app/kalender'
    | '/app/keuangan'
    | '/app/resep'
    | '/app/tugas'
    | '/app'
    | '/app/resep/$resepId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/kebijakan'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/akun'
    | '/app/belanja'
    | '/app/feed'
    | '/app/kalender'
    | '/app/keuangan'
    | '/app/resep'
    | '/app/tugas'
    | '/app/'
    | '/app/resep/$resepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  KebijakanRoute: typeof KebijakanRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan': {
      id: '/kebijakan'
      path: '/kebijakan'
      fullPath: '/kebijakan'
      preLoaderRoute: typeof KebijakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tugas': {
      id: '/app/tugas'
      path: '/tugas'
      fullPath: '/app/tugas'
      preLoaderRoute: typeof AppTugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resep': {
      id: '/app/resep'
      path: '/resep'
      fullPath: '/app/resep'
      preLoaderRoute: typeof AppResepRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keuangan': {
      id: '/app/keuangan'
      path: '/keuangan'
      fullPath: '/app/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kalender': {
      id: '/app/kalender'
      path: '/kalender'
      fullPath: '/app/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/belanja': {
      id: '/app/belanja'
      path: '/belanja'
      fullPath: '/app/belanja'
      preLoaderRoute: typeof AppBelanjaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/akun': {
      id: '/app/akun'
      path: '/akun'
      fullPath: '/app/akun'
      preLoaderRoute: typeof AppAkunRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resep/$resepId': {
      id: '/app/resep/$resepId'
      path: '/$resepId'
      fullPath: '/app/resep/$resepId'
      preLoaderRoute: typeof AppResepResepIdRouteImport
      parentRoute: typeof AppResepRoute
    }
  }
}

interface AppResepRouteChildren {
  AppResepResepIdRoute: typeof AppResepResepIdRoute
}

const AppResepRouteChildren: AppResepRouteChildren = {
  AppResepResepIdRoute: AppResepResepIdRoute,
}

const AppResepRouteWithChildren = AppResepRoute._addFileChildren(
  AppResepRouteChildren,
)

interface AppRouteChildren {
  AppAkunRoute: typeof AppAkunRoute
  AppBelanjaRoute: typeof AppBelanjaRoute
  AppFeedRoute: typeof AppFeedRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppResepRoute: typeof AppResepRouteWithChildren
  AppTugasRoute: typeof AppTugasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAkunRoute: AppAkunRoute,
  AppBelanjaRoute: AppBelanjaRoute,
  AppFeedRoute: AppFeedRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppKeuanganRoute: AppKeuanganRoute,
  AppResepRoute: AppResepRouteWithChildren,
  AppTugasRoute: AppTugasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  KebijakanRoute: KebijakanRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
